### ISSUE TITLE
Moved files do not register changes

### ISSUE THREAD

**Issue by kovmir** [sakhmatd/swege#1]
If you move a file inside the website folder and run swege, then it will act like nothing happened telling you that the site is up to date.

If you do the same with a folder, then, inside the destination folder, it will copy the moved one to a new location, but swege will not delete it from the old place.

**Comment by sakhmatd** [comment]
> If you move a file inside the website folder and run swege, then it will act like nothing happened telling you that the site is up to date.

I could not reproduce. Moving a file should create a new file for swege to detect and reproduce in the site folder. Which OS and file system are you running swege on?

That being said, 

> If you do the same with a folder, then, inside the destination folder, it will copy the moved one to a new location, but swege will not delete it from the old place.

this is true. The only real way to fix this would be to check for stale files after copying, but that would come with a small performance hit. I will likely add a relevant switch to the config.

**Comment by kovmir** [comment]
>I could not reproduce. Moving a file should create a new file for swege to detect and reproduce in the site folder. Which OS and file system are you running swege on?

https://i.imgur.com/J7yZ0pi.png
FreeBSD 12.2-RELEASE

**Comment by sakhmatd** [comment]
First part of the bug should be fixed now.

Since this issue references two separate bugs, I have created another issue.
#2 should be easier to fix once I update the manifests to be binary.
